[package]
name = "hexgrid"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2"
thiserror = "1.0.37"

[dev-dependencies]
minifb = "0.19"
raqote = "0.8"
