[package]
name = "hexgrid"
version = "0.1.0"
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.4.0"
thiserror = "1.0.40"

[dev-dependencies]
minifb = "0.24.0"
raqote = "0.8.2"
